[env:nodemcu-32s]
platform = https://github.com/platformio/platform-espressif32.git
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps =
    plerup/EspSoftwareSerial
    emelianov/modbus-esp8266